@startuml
|被保险人|
start
:输入保险单号码、身份证号码;
:上传事故材料\n(驾驶证、行驶证、责任书扫描件);
split
  :准备缺少的材料;
  ->[资料不完整] 回到基本流1;
split again
  ->[资料完整] 提交资料;
end split

|保险公司|
:检查保单是否有效;
split
  :拒绝索赔;
  ->[保单不在有效期内] 结案;
split again
  :指定工作人员复核和确认事故状况和责任;
  :检查所有事故相关细节都在保单条款范围内;
split
  :拒绝索赔, 告知客户;
  ->[事故符合免责条款] 结案;
split again
  :依条款计算索赔金额;
  :向被保险人账户转账;
  -> 结案;
end split
end split

end
@enduml
